// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}

export { }
