// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn: typeof import('./src/components/Btn.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Output: typeof import('./src/components/Output.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
